# MusicalInstruments - Recordings Configuration

permissions:
  # Permission required to run /instruments recordings access <recording_id>
  # Gives the sender a Bard's Notation (share scroll) for the specified recording.
  recordings-access: "musicalinstruments.recordings.access"

playback:
  volume: 4.0               # 1 Volume = 16 blocks of range (in this case, 64 blocks)
  pitch: 1.0                # Range between 0.5 (half speed) and 2.0 (double speed)